/**
 * Hi-MO X10 产品矩阵（来源：Google Drive 产品资料包 Product-Segments）
 * 用于并行选型站推荐；与对比工具的 ModuleRecord 库相互独立、可互跳。
 */

export type ProductSegmentBand = "residential" | "medium" | "large";
export type ProductGlass = "single" | "dual";
export type ProductGeneration = "monofacial" | "bifacial" | "transparent";

export interface ProductSeriesFeatures {
  /** 防积灰边框（F 版型） */
  antiDust: boolean;
  /** 防眩光 */
  antiGlare: boolean;
  /** 轻质 / 低载荷 */
  lightweight: boolean;
  /** 防局部过热 / 抗热斑（HPBC） */
  antiHotspot: boolean;
  /** 抗阴影遮挡（HPBC） */
  antiShading: boolean;
  /** 盐雾（沿海） */
  saltMist: boolean;
  /** 氨气（农牧） */
  ammonia: boolean;
  /** 冰雹 */
  hail: boolean;
}

export interface ProductSeries {
  id: string;
  modelFamily: string;
  nameZh: string;
  nameEn: string;
  powerMinWp: number;
  powerMaxWp: number;
  /** 代表功率（用于跳转对比工具） */
  representativePowerWp: number;
  /** 对比库中常见代表型号 */
  representativeModel: string;
  segment: ProductSegmentBand;
  generation: ProductGeneration;
  glass: ProductGlass;
  cellOrientation: string;
  dimensionMm: string;
  weightKg: number;
  efficiencyMaxPct: number;
  firstYearDegradationPct: number;
  annualDegradationPct: number;
  pmpTempCoef: number;
  productWarrantyYears: number;
  performanceWarrantyYears: number;
  features: ProductSeriesFeatures;
  highlightsZh: string[];
  highlightsEn: string[];
  imageSrc?: string;
  datasheetFile?: string;
}

const BC_BASE: Pick<
  ProductSeriesFeatures,
  "antiHotspot" | "antiShading" | "saltMist" | "ammonia"
> = {
  antiHotspot: true,
  antiShading: true,
  saltMist: true,
  ammonia: true,
};

/**
 * Drive 产品矩阵整理后的可售系列。
 * 质保年限以 AU《Limited Warranty for LONGi Hi-MOX10 Solar Modules
 * (Distributed Generation Market)》型号表为准；机械/电性能以对应 AU Datasheet 为准。
 */
export const PRODUCT_MATRIX: ProductSeries[] = [
  {
    id: "LR7-54HVB",
    modelFamily: "LR7-54HVB",
    nameZh: "Hi-MO X10 户用 · HVB",
    nameEn: "Hi-MO X10 Residential · HVB",
    powerMinWp: 475,
    powerMaxWp: 495,
    representativePowerWp: 475,
    representativeModel: "LR7-54HVB-475M",
    segment: "residential",
    generation: "monofacial",
    glass: "single",
    cellOrientation: "108 (6×18)",
    dimensionMm: "1800×1134×30",
    weightKg: 21.6,
    efficiencyMaxPct: 24.3,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 30,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: false,
      antiGlare: true,
      lightweight: false,
      hail: true,
    },
    highlightsZh: ["户用场景", "防眩光认证", "抗热斑 / 抗遮挡"],
    highlightsEn: ["Residential", "Anti-glare certified", "Anti-hotspot / anti-shading"],
    imageSrc: "/products/LR7-54HVB.png",
    datasheetFile: "AU_Datasheet_X10_LR7-54HVB_475-495.pdf",
  },
  {
    id: "LR7-54HVH",
    modelFamily: "LR7-54HVH",
    nameZh: "Hi-MO X10 户用 · HVH",
    nameEn: "Hi-MO X10 Residential · HVH",
    powerMinWp: 475,
    powerMaxWp: 500,
    representativePowerWp: 475,
    representativeModel: "LR7-54HVH-475M",
    segment: "residential",
    generation: "monofacial",
    glass: "single",
    cellOrientation: "108 (6×18)",
    dimensionMm: "1800×1134×30",
    weightKg: 21.6,
    efficiencyMaxPct: 24.5,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 25,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: false,
      antiGlare: true,
      lightweight: false,
      hail: true,
    },
    highlightsZh: ["高效单玻", "遮挡下温升更低", "A+ 抗遮挡"],
    highlightsEn: ["High-efficiency mono", "Lower shade temperature", "A+ anti-shading"],
    imageSrc: "/products/LR7-54HVH.png",
    datasheetFile: "AU_Datasheet_X10_LR7-54HVH_475-500.pdf",
  },
  {
    id: "LR7-54HVHF",
    modelFamily: "LR7-54HVHF",
    nameZh: "Hi-MO X10 户用 · 防积灰 HVHF",
    nameEn: "Hi-MO X10 Residential · Anti-Dust HVHF",
    powerMinWp: 480,
    powerMaxWp: 500,
    representativePowerWp: 480,
    representativeModel: "LR7-54HVHF-480M",
    segment: "residential",
    generation: "monofacial",
    glass: "single",
    cellOrientation: "108 (6×18)",
    dimensionMm: "1800×1134×30",
    weightKg: 21.6,
    efficiencyMaxPct: 24.5,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 25,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: true,
      antiGlare: false,
      lightweight: false,
      hail: false,
    },
    highlightsZh: ["防积灰边框", "降低清洗频次", "户用分布式"],
    highlightsEn: ["Anti-dust frame", "Less cleaning", "Residential DG"],
    datasheetFile: "AU_Datasheet_X10_LR7-54HVHF_480-500.pdf",
  },
  {
    id: "LR7-54HVDT",
    modelFamily: "LR7-54HVDT",
    nameZh: "Hi-MO X10 户用 · 透明双面 HVDT",
    nameEn: "Hi-MO X10 Residential · Transparent Bifacial HVDT",
    powerMinWp: 465,
    powerMaxWp: 495,
    representativePowerWp: 475,
    representativeModel: "LR7-54HVD-T-475M",
    segment: "residential",
    generation: "transparent",
    glass: "dual",
    cellOrientation: "108 (6×18)",
    dimensionMm: "1800×1134×30",
    weightKg: 23.5,
    efficiencyMaxPct: 24.25,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 25,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: false,
      antiGlare: false,
      lightweight: false,
      hail: false,
    },
    highlightsZh: ["透明双玻设计", "双面增益", "无栅线美学"],
    highlightsEn: ["Transparent dual-glass", "Bifacial gain", "Gridless look"],
    datasheetFile: "AU_Datasheet_X10_LR7-54HVDT_465-495.pdf",
  },
  {
    id: "LR7-60HVH",
    modelFamily: "LR7-60HVH",
    nameZh: "Hi-MO X10 中版型 · HVH",
    nameEn: "Hi-MO X10 Mid-size · HVH",
    powerMinWp: 535,
    powerMaxWp: 560,
    representativePowerWp: 540,
    representativeModel: "LR7-60HVH-540M",
    segment: "medium",
    generation: "monofacial",
    glass: "single",
    cellOrientation: "120 (6×20)",
    dimensionMm: "1990×1134×30",
    weightKg: 25,
    efficiencyMaxPct: 24.8,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 25,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: false,
      antiGlare: false,
      lightweight: false,
      hail: true,
    },
    highlightsZh: ["中版型单玻", "短边夹具友好", "HPBC 2.0"],
    highlightsEn: ["Mid mono glass", "Short-clamp friendly", "HPBC 2.0"],
    datasheetFile: "AU_Datasheet_X10_LR7-60HVH_535-560.pdf",
  },
  {
    id: "LR7-60HVD",
    modelFamily: "LR7-60HVD",
    nameZh: "Hi-MO X10 中版型 · 双面 HVD",
    nameEn: "Hi-MO X10 Mid-size · Bifacial HVD",
    powerMinWp: 530,
    powerMaxWp: 555,
    representativePowerWp: 540,
    representativeModel: "LR7-60HVD-540M",
    segment: "medium",
    generation: "bifacial",
    glass: "dual",
    cellOrientation: "120 (6×20)",
    dimensionMm: "1990×1134×30",
    weightKg: 28,
    efficiencyMaxPct: 24.6,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 25,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: false,
      antiGlare: false,
      lightweight: false,
      hail: true,
    },
    highlightsZh: ["双玻双面", "工商业屋顶", "高机械载荷"],
    highlightsEn: ["Dual-glass bifacial", "C&I rooftops", "High mechanical load"],
    datasheetFile: "AU_Datasheet_X10_LR7-60HVD_530-555.pdf",
  },
  {
    id: "LR7-60HVHL",
    modelFamily: "LR7-60HVHL",
    nameZh: "Hi-MO X10 中版型 · 轻质 HVHL",
    nameEn: "Hi-MO X10 Mid-size · Lightweight HVHL",
    powerMinWp: 535,
    powerMaxWp: 560,
    representativePowerWp: 540,
    representativeModel: "LR7-60HVHL-540M",
    segment: "medium",
    generation: "monofacial",
    glass: "single",
    cellOrientation: "120 (6×20)",
    dimensionMm: "1990×1134×30",
    weightKg: 16.3,
    efficiencyMaxPct: 24.8,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 25,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: false,
      antiGlare: false,
      lightweight: true,
      hail: true,
    },
    highlightsZh: ["轻约 16.3 kg", "低承重屋顶", "相对常规减重可达 42%"],
    highlightsEn: ["~16.3 kg", "Low load-bearing roofs", "Up to 42% lighter"],
    datasheetFile: "AU_Datasheet_X10_LR7-60HVHL_535-560.pdf",
  },
  /** 以下系列与 Drive「01-产品矩阵 / Product-Segments」文件夹一一对应 */
  {
    id: "LR7-72HVD",
    modelFamily: "LR7-72HVD",
    nameZh: "Hi-MO X10 大版型 · 双面 HVD",
    nameEn: "Hi-MO X10 Large · Bifacial HVD",
    powerMinWp: 640,
    powerMaxWp: 665,
    representativePowerWp: 650,
    representativeModel: "LR7-72HVD-650M",
    segment: "large",
    generation: "bifacial",
    glass: "dual",
    cellOrientation: "144 (6×24)",
    dimensionMm: "2382×1134×30",
    weightKg: 33.5,
    efficiencyMaxPct: 24.6,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 15,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: false,
      antiGlare: true,
      lightweight: false,
      hail: true,
    },
    highlightsZh: ["大版型双面", "防眩光认证可选", "遮挡下温升更低"],
    highlightsEn: ["Large bifacial", "Anti-glare option", "Lower shade temperature"],
    imageSrc: "/products/LR7-72HVD.png",
    datasheetFile: "AU_Datasheet_X10_LR7-72HVD_640-665.pdf",
  },
  {
    id: "LR7-72HVDF",
    modelFamily: "LR7-72HVDF",
    nameZh: "Hi-MO X10 大版型 · 防积灰双面 HVDF",
    nameEn: "Hi-MO X10 Large · Anti-Dust Bifacial HVDF",
    powerMinWp: 640,
    powerMaxWp: 665,
    representativePowerWp: 650,
    representativeModel: "LR7-72HVDF-650M",
    segment: "large",
    generation: "bifacial",
    glass: "dual",
    cellOrientation: "144 (6×24)",
    dimensionMm: "2382×1134×30",
    weightKg: 33.5,
    efficiencyMaxPct: 24.6,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 15,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: true,
      antiGlare: false,
      lightweight: false,
      hail: true,
    },
    highlightsZh: ["大版型双面", "防积灰边框", "工商业屋顶"],
    highlightsEn: ["Large bifacial", "Anti-dust frame", "C&I rooftops"],
    datasheetFile: "AU_Datasheet_X10_LR7-72HVDF_640-665.pdf",
  },
  {
    id: "LR7-72HVH",
    modelFamily: "LR7-72HVH",
    nameZh: "Hi-MO X10 大版型 · 单面 HVH",
    nameEn: "Hi-MO X10 Large · Monofacial HVH",
    powerMinWp: 645,
    powerMaxWp: 670,
    representativePowerWp: 650,
    representativeModel: "LR7-72HVH-650M",
    segment: "large",
    generation: "monofacial",
    glass: "single",
    cellOrientation: "144 (6×24)",
    dimensionMm: "2382×1134×30",
    weightKg: 28.5,
    efficiencyMaxPct: 24.8,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 15,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: false,
      antiGlare: true,
      lightweight: false,
      hail: true,
    },
    highlightsZh: ["大版型单玻", "高效输出", "HPBC 2.0"],
    highlightsEn: ["Large mono glass", "High output", "HPBC 2.0"],
    datasheetFile: "AU_Datasheet_X10_LR7-72HVH_645-670.pdf",
  },
  {
    id: "LR7-72HVHF",
    modelFamily: "LR7-72HVHF",
    nameZh: "Hi-MO X10 大版型 · 防积灰单面 HVHF",
    nameEn: "Hi-MO X10 Large · Anti-Dust Monofacial HVHF",
    powerMinWp: 640,
    powerMaxWp: 670,
    representativePowerWp: 650,
    representativeModel: "LR7-72HVHF-650M",
    segment: "large",
    generation: "monofacial",
    glass: "single",
    cellOrientation: "144 (6×24)",
    dimensionMm: "2382×1134×30",
    weightKg: 28.5,
    efficiencyMaxPct: 24.8,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 15,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: true,
      antiGlare: false,
      lightweight: false,
      hail: true,
    },
    highlightsZh: ["大版型单玻", "防积灰边框", "降低清洗频次"],
    highlightsEn: ["Large mono glass", "Anti-dust frame", "Less cleaning"],
    datasheetFile: "AU_Datasheet_X10_LR7-72HVHF_640-670.pdf",
  },
  {
    id: "LR8-66HVD",
    modelFamily: "LR8-66HVD",
    nameZh: "Hi-MO X10 大版型 · LR8-66 双面 HVD",
    nameEn: "Hi-MO X10 Large · LR8-66 Bifacial HVD",
    powerMinWp: 640,
    powerMaxWp: 670,
    representativePowerWp: 650,
    representativeModel: "LR8-66HVD-650M",
    segment: "large",
    generation: "bifacial",
    glass: "dual",
    cellOrientation: "132 (6×22)",
    dimensionMm: "2382×1134×30",
    weightKg: 32.5,
    efficiencyMaxPct: 24.8,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 15,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: false,
      antiGlare: true,
      lightweight: false,
      hail: true,
    },
    highlightsZh: ["LR8-66 双面", "HPBC 2.0", "工商业屋顶"],
    highlightsEn: ["LR8-66 bifacial", "HPBC 2.0", "C&I rooftops"],
    datasheetFile: "AU_Datasheet_X10_LR8-66HVD_640-670.pdf",
  },
  {
    id: "LR8-66HVDF",
    modelFamily: "LR8-66HVDF",
    nameZh: "Hi-MO X10 大版型 · LR8-66 防积灰双面 HVDF",
    nameEn: "Hi-MO X10 Large · LR8-66 Anti-Dust Bifacial HVDF",
    powerMinWp: 640,
    powerMaxWp: 665,
    representativePowerWp: 650,
    representativeModel: "LR8-66HVDF-650M",
    segment: "large",
    generation: "bifacial",
    glass: "dual",
    cellOrientation: "132 (6×22)",
    dimensionMm: "2382×1134×30",
    weightKg: 33.5,
    efficiencyMaxPct: 24.62,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 15,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: true,
      antiGlare: false,
      lightweight: false,
      hail: true,
    },
    highlightsZh: ["LR8-66 双面", "防积灰边框", "HPBC 2.0"],
    highlightsEn: ["LR8-66 bifacial", "Anti-dust frame", "HPBC 2.0"],
    datasheetFile: "AU_Datasheet_X10_LR8-66HVDF_640-665.pdf",
  },
  {
    id: "LR8-66HYD",
    modelFamily: "LR8-66HYD",
    nameZh: "Hi-MO X10 大版型 · LR8-66 HYD",
    nameEn: "Hi-MO X10 Large · LR8-66 HYD",
    powerMinWp: 640,
    powerMaxWp: 670,
    representativePowerWp: 650,
    representativeModel: "LR8-66HYD-650M",
    segment: "large",
    generation: "bifacial",
    glass: "dual",
    cellOrientation: "132 (6×22)",
    dimensionMm: "2382×1134×30",
    weightKg: 32.7,
    efficiencyMaxPct: 24.8,
    firstYearDegradationPct: 1,
    annualDegradationPct: 0.35,
    pmpTempCoef: -0.26,
    productWarrantyYears: 12,
    performanceWarrantyYears: 30,
    features: {
      ...BC_BASE,
      antiDust: false,
      antiGlare: false,
      lightweight: false,
      hail: true,
    },
    highlightsZh: ["LR8-66 HYD", "IceShield 可选", "双玻双面"],
    highlightsEn: ["LR8-66 HYD", "IceShield option", "Dual-glass bifacial"],
    datasheetFile: "Datasheet_LR8-66HYD_Glass2.0+2_635-670_V5.0_EN.pdf",
  },
];

export function getProductSeriesById(id: string): ProductSeries | undefined {
  return PRODUCT_MATRIX.find((p) => p.id === id);
}
